version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: etl_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - etl_pg_data:/var/lib/postgresql/data
  etl_worker:
    build: .
    container_name: etl_python_worker
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  etl_pg_data:
