services:
  postgres:
    image: postgres:15-alpine
    container_name: etl_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_password
      POSTGRES_DB: etl_db
    ports:
      - "5432:5432"
    volumes:
      - etl_pg_data:/var/lib/postgresql/data
  etl_worker:
    build: .
    container_name: etl_python_worker
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres

  redis:
    image: redis:7.4-alpine
    container_name: first_redis
    env_file:
      - .env
    volumes:
      - ./.redis_data:/data
    restart: unless-stopped
    ports:
      - "${REDIS_PORT}:6379"
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
  minio:
    image: minio/minio
    container_name: etl_minio
    env_file:
      - .env
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    volumes:
      - ./.minio_data:/data
    command: server /data --console-address ":9001"
volumes:
  etl_pg_data:
